name: API Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: set Nx  
        uses: nrwl/nx-set-shas@v3 
      - run: npx nx format:check
      - run: npx nx affected -t lint,test,build --parallel=3
      - name: Run API tests
        run: nx test
        env:
          CI: true  

